/**:
  ros__parameters:

    ### GENERIC PARAMS
    config_name: 'vitl14_basic'
    
    ### AUDIO PARAMS - these should not change across experiments

    n_channels: 16
    sample_rate: 44100
    downsample_rate: 32000
    frame_size: 44100
    scene_size: 44100
    scene_index: [0]
    labels: ['airport', 'bus', 'metro', 'metro_station', 'park', 'public_square', 'shopping_mall', 'street_pedestrian', 'street_traffic', 'tram']

    # Model path params
    project_name: DCASE23_Task1
    wandb_id: 'c0a7nzin'

    # Mel pre-processing parameters
    resample_rate: 32000
    window_size: 3072
    hop_size: 500
    n_fft: 4096
    n_mels: 256
    freqm: 48
    timem: 0
    fmin: 0
    fmax: 0
    fmin_aug_range: 1
    fmax_aug_range: 1000

    # Model parameters
    n_classes: 10
    in_channels: 1
    base_channels: 32
    channels_multiplier: 2.3
    expansion_rate: 3

    ### CLIP SCENE ESTIMATION PARAMS

    num_est_interval_samples: 15 # Number of samples 
    scene_labels: ['campus','courtyard','lab','lobby']
    scene_descriptions: ['college campus','a courtyard','a lab', 'a lobby']
    clip_model: 'ViT-L/14'


### AUDIO BAYES ESTIMATOR PARAMS
/bayes_audio_scene_est:
  ros__parameters:

    scene_labels: ['campus','courtyard','lab','lobby']
    scene_prior: [.25,.25,.25,.25]

    sensor_names: ['dcase23']

    dcase23:
      obs_labels: ['airport', 'bus', 'metro', 'metro_station','park','public_square','shopping_mall','street_pedestrian','street_traffic','tram']
      sensor_model_coeffs: [8., 17., 49., 22., 191., 7., 1., 1., 44., 1948.,
                            4., 305., 5., 8., 765., 1., 1., 2., 22., 1362.,
                            22., 156., 2125., 33., 79., 2., 1., 2., 66., 21.,
                            459., 47., 208., 475., 971., 1., 70., 19., 22., 179.]
      topic: 'audio_scene_category'

### CLIP BAYES ESTIMATOR PARAMS
/bayes_clip_scene_est:
  ros__parameters:

    scene_labels: ['campus','courtyard','lab','lobby']
    scene_prior: [.25,.25,.25,.25]

    sensor_names: ['clip']

    clip:
      obs_labels: ['campus','courtyard','lab','lobby']
      sensor_model_coeffs: [38152., 490., 13., 1.,
                            39497., 2463., 949., 2.,
                            1., 1., 39176., 3018.,
                            348., 483., 34., 40578.]
      topic: 'clip_scene_category'

### FUSED BAYES ESTIMATOR PARAMS
/bayes_fused_scene_est:
  ros__parameters:

    scene_labels: ['campus','courtyard','lab','lobby']
    scene_prior: [.25,.25,.25,.25]

    sensor_names: ['clip','dcase23']

    clip:
      obs_labels: ['campus','courtyard','lab','lobby']
      sensor_model_coeffs: [38152., 490., 13., 1.,
                            39497., 2463., 949., 2.,
                            1., 1., 39176., 3018.,
                            348., 483., 34., 40578.]
      topic: 'clip_scene_category'

    dcase23:
      obs_labels: ['airport', 'bus', 'metro', 'metro_station','park','public_square','shopping_mall','street_pedestrian','street_traffic','tram']
      sensor_model_coeffs: [8., 17., 49., 22., 191., 7., 1., 1., 44., 1948.,
                            4., 305., 5., 8., 765., 1., 1., 2., 22., 1362.,
                            22., 156., 2125., 33., 79., 2., 1., 2., 66., 21.,
                            459., 47., 208., 475., 971., 1., 70., 19., 22., 179.]
      topic: 'audio_scene_category'