/bayes_scene_category_est:
  ros__parameters:
    callback_period_sec: 1.0
    scene_labels: ['home', 'back_yard', 'neighborhood','park']
    scene_prior: [.25,.25,.25,.25]

    sensor_names: ['clip','dcase23']

    clip:
      obs_labels: ['home', 'back_yard', 'neighborhood', 'park','lab','classroom','campus','store','city_street']
      sensor_model_coeffs: [287., 1., 1., 1., 29., 3., 1., 5., 1.,
                            2., 318., 1., 3., 1., 1., 1., 1., 1.,
                            1., 46., 259., 12., 1., 1., 4., 1., 4.,
                            2., 40., 18., 231., 1., 1., 34., 1., 1.]
      topic: 'clip_scene_category'

    dcase23:
      obs_labels: ['airport', 'bus', 'metro', 'metro_station','park','public_square','shopping_mall','street_pedestrian','street_traffic','tram']
      sensor_model_coeffs: [34., 32., 18., 83., 108., 2., 1., 2., 2., 48.,
                            2., 39., 9., 17., 252., 2., 2., 2., 1., 4.,
                            3., 18., 9., 9., 272., 5., 2., 1., 7., 4.,
                            1., 13., 2., 1., 295., 1., 1., 1., 11., 4.]
      topic: 'audio_scene_category'