/clip_scene_rec:
  ros__parameters:
    callback_period_sec: 1.0
    scene_labels: ['home', 'back_yard', 'neighborhood']
    scene_descriptions: ['inside a home', 'a back yard', 'a neighborhood']
    clip_model: 'ViT-B/32'