/**:
  ros__parameters:
    callback_period_sec: 1.0
    scene_labels: ['college-campus','courtyard','laboratory','lobby']
    scene_descriptions: ['a picture of a college campus','a picture of a courtyard','a picture of a laboratory','a picture of a lobby']
    clip_model: 'ViT-B/32'